-- Table: public.broth

-- DROP TABLE IF EXISTS public.broth;

CREATE TABLE IF NOT EXISTS public.broth
(
    price double precision,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    image_active character varying(255) COLLATE pg_catalog."default",
    image_inactive character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT broth_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.broth
    OWNER to admin;
